### ISSUE TITLE
cfbundleidentifier does not exist?

### ISSUE THREAD

**Issue by stucodervets** [MrToph/quiz-app#1]
I get the dreaded cfbundleidentifier does not exist when I run react-native run-ios. How to resolve?

**Comment by stucodervets** [comment]
When I open and build in XCode it gives me the error: linker command failed with exit code 1. ideas?

**Comment by MrToph** [comment]
I developed this app only with Android in mind. I never tested it with iOS. It might, therefore, be that some iOS build settings are broken.

How did you even end up in this repo, I didn't intend anyone else to try running the code, haha.

**Comment by MrToph** [comment]
Maybe this can help: https://github.com/facebook/react-native/issues/7308
